// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserEvents_Events int32

const (
	UserEvents_joined UserEvents_Events = 0
	UserEvents_left   UserEvents_Events = 1
)

var UserEvents_Events_name = map[int32]string{
	0: "joined",
	1: "left",
}

var UserEvents_Events_value = map[string]int32{
	"joined": 0,
	"left":   1,
}

func (x UserEvents_Events) String() string {
	return proto.EnumName(UserEvents_Events_name, int32(x))
}

func (UserEvents_Events) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8, 0}
}

type JoinRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type JoinResponse struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *JoinResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ChatMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChatMessage) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ChatMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ChatMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageUpdate struct {
	IsRead               bool     `protobuf:"varint,1,opt,name=isRead,proto3" json:"isRead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUpdate) Reset()         { *m = MessageUpdate{} }
func (m *MessageUpdate) String() string { return proto.CompactTextString(m) }
func (*MessageUpdate) ProtoMessage()    {}
func (*MessageUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *MessageUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUpdate.Unmarshal(m, b)
}
func (m *MessageUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUpdate.Marshal(b, m, deterministic)
}
func (m *MessageUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUpdate.Merge(m, src)
}
func (m *MessageUpdate) XXX_Size() int {
	return xxx_messageInfo_MessageUpdate.Size(m)
}
func (m *MessageUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUpdate proto.InternalMessageInfo

func (m *MessageUpdate) GetIsRead() bool {
	if m != nil {
		return m.IsRead
	}
	return false
}

type ReadMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMessage) Reset()         { *m = ReadMessage{} }
func (m *ReadMessage) String() string { return proto.CompactTextString(m) }
func (*ReadMessage) ProtoMessage()    {}
func (*ReadMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ReadMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMessage.Unmarshal(m, b)
}
func (m *ReadMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMessage.Marshal(b, m, deterministic)
}
func (m *ReadMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMessage.Merge(m, src)
}
func (m *ReadMessage) XXX_Size() int {
	return xxx_messageInfo_ReadMessage.Size(m)
}
func (m *ReadMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMessage proto.InternalMessageInfo

func (m *ReadMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

type MessageResponse struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	RequestId            string   `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func (m *MessageResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserEvents struct {
	UserId               string            `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Events               UserEvents_Events `protobuf:"varint,2,opt,name=events,proto3,enum=chaty.UserEvents_Events" json:"events,omitempty"`
	UserName             string            `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserEvents) Reset()         { *m = UserEvents{} }
func (m *UserEvents) String() string { return proto.CompactTextString(m) }
func (*UserEvents) ProtoMessage()    {}
func (*UserEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *UserEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvents.Unmarshal(m, b)
}
func (m *UserEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvents.Marshal(b, m, deterministic)
}
func (m *UserEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvents.Merge(m, src)
}
func (m *UserEvents) XXX_Size() int {
	return xxx_messageInfo_UserEvents.Size(m)
}
func (m *UserEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvents.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvents proto.InternalMessageInfo

func (m *UserEvents) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserEvents) GetEvents() UserEvents_Events {
	if m != nil {
		return m.Events
	}
	return UserEvents_joined
}

func (m *UserEvents) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type TypingState struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsTyping             bool     `protobuf:"varint,2,opt,name=isTyping,proto3" json:"isTyping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypingState) Reset()         { *m = TypingState{} }
func (m *TypingState) String() string { return proto.CompactTextString(m) }
func (*TypingState) ProtoMessage()    {}
func (*TypingState) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *TypingState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypingState.Unmarshal(m, b)
}
func (m *TypingState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypingState.Marshal(b, m, deterministic)
}
func (m *TypingState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypingState.Merge(m, src)
}
func (m *TypingState) XXX_Size() int {
	return xxx_messageInfo_TypingState.Size(m)
}
func (m *TypingState) XXX_DiscardUnknown() {
	xxx_messageInfo_TypingState.DiscardUnknown(m)
}

var xxx_messageInfo_TypingState proto.InternalMessageInfo

func (m *TypingState) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TypingState) GetIsTyping() bool {
	if m != nil {
		return m.IsTyping
	}
	return false
}

type ListUsers struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsers) Reset()         { *m = ListUsers{} }
func (m *ListUsers) String() string { return proto.CompactTextString(m) }
func (*ListUsers) ProtoMessage()    {}
func (*ListUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ListUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsers.Unmarshal(m, b)
}
func (m *ListUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsers.Marshal(b, m, deterministic)
}
func (m *ListUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsers.Merge(m, src)
}
func (m *ListUsers) XXX_Size() int {
	return xxx_messageInfo_ListUsers.Size(m)
}
func (m *ListUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsers.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsers proto.InternalMessageInfo

func (m *ListUsers) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ClientEvents struct {
	// Types that are valid to be assigned to Event:
	//	*ClientEvents_JoinRequest
	//	*ClientEvents_ChatMessage
	//	*ClientEvents_TypingState
	//	*ClientEvents_ListUsers
	//	*ClientEvents_ReadMessage
	Event                isClientEvents_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClientEvents) Reset()         { *m = ClientEvents{} }
func (m *ClientEvents) String() string { return proto.CompactTextString(m) }
func (*ClientEvents) ProtoMessage()    {}
func (*ClientEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ClientEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientEvents.Unmarshal(m, b)
}
func (m *ClientEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientEvents.Marshal(b, m, deterministic)
}
func (m *ClientEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientEvents.Merge(m, src)
}
func (m *ClientEvents) XXX_Size() int {
	return xxx_messageInfo_ClientEvents.Size(m)
}
func (m *ClientEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ClientEvents proto.InternalMessageInfo

type isClientEvents_Event interface {
	isClientEvents_Event()
}

type ClientEvents_JoinRequest struct {
	JoinRequest *JoinRequest `protobuf:"bytes,1,opt,name=joinRequest,proto3,oneof"`
}

type ClientEvents_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,2,opt,name=chatMessage,proto3,oneof"`
}

type ClientEvents_TypingState struct {
	TypingState *TypingState `protobuf:"bytes,3,opt,name=typingState,proto3,oneof"`
}

type ClientEvents_ListUsers struct {
	ListUsers *ListUsers `protobuf:"bytes,4,opt,name=listUsers,proto3,oneof"`
}

type ClientEvents_ReadMessage struct {
	ReadMessage *ReadMessage `protobuf:"bytes,5,opt,name=readMessage,proto3,oneof"`
}

func (*ClientEvents_JoinRequest) isClientEvents_Event() {}

func (*ClientEvents_ChatMessage) isClientEvents_Event() {}

func (*ClientEvents_TypingState) isClientEvents_Event() {}

func (*ClientEvents_ListUsers) isClientEvents_Event() {}

func (*ClientEvents_ReadMessage) isClientEvents_Event() {}

func (m *ClientEvents) GetEvent() isClientEvents_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ClientEvents) GetJoinRequest() *JoinRequest {
	if x, ok := m.GetEvent().(*ClientEvents_JoinRequest); ok {
		return x.JoinRequest
	}
	return nil
}

func (m *ClientEvents) GetChatMessage() *ChatMessage {
	if x, ok := m.GetEvent().(*ClientEvents_ChatMessage); ok {
		return x.ChatMessage
	}
	return nil
}

func (m *ClientEvents) GetTypingState() *TypingState {
	if x, ok := m.GetEvent().(*ClientEvents_TypingState); ok {
		return x.TypingState
	}
	return nil
}

func (m *ClientEvents) GetListUsers() *ListUsers {
	if x, ok := m.GetEvent().(*ClientEvents_ListUsers); ok {
		return x.ListUsers
	}
	return nil
}

func (m *ClientEvents) GetReadMessage() *ReadMessage {
	if x, ok := m.GetEvent().(*ClientEvents_ReadMessage); ok {
		return x.ReadMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientEvents) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientEvents_JoinRequest)(nil),
		(*ClientEvents_ChatMessage)(nil),
		(*ClientEvents_TypingState)(nil),
		(*ClientEvents_ListUsers)(nil),
		(*ClientEvents_ReadMessage)(nil),
	}
}

type ServerEvents struct {
	// Types that are valid to be assigned to Event:
	//	*ServerEvents_JoinResponse
	//	*ServerEvents_MessageResponse
	//	*ServerEvents_Users
	//	*ServerEvents_UserEvents
	//	*ServerEvents_ChatMessage
	//	*ServerEvents_TypingState
	//	*ServerEvents_MessageUpdate
	Event                isServerEvents_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ServerEvents) Reset()         { *m = ServerEvents{} }
func (m *ServerEvents) String() string { return proto.CompactTextString(m) }
func (*ServerEvents) ProtoMessage()    {}
func (*ServerEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ServerEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerEvents.Unmarshal(m, b)
}
func (m *ServerEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerEvents.Marshal(b, m, deterministic)
}
func (m *ServerEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerEvents.Merge(m, src)
}
func (m *ServerEvents) XXX_Size() int {
	return xxx_messageInfo_ServerEvents.Size(m)
}
func (m *ServerEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ServerEvents proto.InternalMessageInfo

type isServerEvents_Event interface {
	isServerEvents_Event()
}

type ServerEvents_JoinResponse struct {
	JoinResponse *JoinResponse `protobuf:"bytes,1,opt,name=joinResponse,proto3,oneof"`
}

type ServerEvents_MessageResponse struct {
	MessageResponse *MessageResponse `protobuf:"bytes,2,opt,name=messageResponse,proto3,oneof"`
}

type ServerEvents_Users struct {
	Users *Users `protobuf:"bytes,3,opt,name=users,proto3,oneof"`
}

type ServerEvents_UserEvents struct {
	UserEvents *UserEvents `protobuf:"bytes,4,opt,name=userEvents,proto3,oneof"`
}

type ServerEvents_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,5,opt,name=chatMessage,proto3,oneof"`
}

type ServerEvents_TypingState struct {
	TypingState *TypingState `protobuf:"bytes,6,opt,name=typingState,proto3,oneof"`
}

type ServerEvents_MessageUpdate struct {
	MessageUpdate *MessageUpdate `protobuf:"bytes,7,opt,name=messageUpdate,proto3,oneof"`
}

func (*ServerEvents_JoinResponse) isServerEvents_Event() {}

func (*ServerEvents_MessageResponse) isServerEvents_Event() {}

func (*ServerEvents_Users) isServerEvents_Event() {}

func (*ServerEvents_UserEvents) isServerEvents_Event() {}

func (*ServerEvents_ChatMessage) isServerEvents_Event() {}

func (*ServerEvents_TypingState) isServerEvents_Event() {}

func (*ServerEvents_MessageUpdate) isServerEvents_Event() {}

func (m *ServerEvents) GetEvent() isServerEvents_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ServerEvents) GetJoinResponse() *JoinResponse {
	if x, ok := m.GetEvent().(*ServerEvents_JoinResponse); ok {
		return x.JoinResponse
	}
	return nil
}

func (m *ServerEvents) GetMessageResponse() *MessageResponse {
	if x, ok := m.GetEvent().(*ServerEvents_MessageResponse); ok {
		return x.MessageResponse
	}
	return nil
}

func (m *ServerEvents) GetUsers() *Users {
	if x, ok := m.GetEvent().(*ServerEvents_Users); ok {
		return x.Users
	}
	return nil
}

func (m *ServerEvents) GetUserEvents() *UserEvents {
	if x, ok := m.GetEvent().(*ServerEvents_UserEvents); ok {
		return x.UserEvents
	}
	return nil
}

func (m *ServerEvents) GetChatMessage() *ChatMessage {
	if x, ok := m.GetEvent().(*ServerEvents_ChatMessage); ok {
		return x.ChatMessage
	}
	return nil
}

func (m *ServerEvents) GetTypingState() *TypingState {
	if x, ok := m.GetEvent().(*ServerEvents_TypingState); ok {
		return x.TypingState
	}
	return nil
}

func (m *ServerEvents) GetMessageUpdate() *MessageUpdate {
	if x, ok := m.GetEvent().(*ServerEvents_MessageUpdate); ok {
		return x.MessageUpdate
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerEvents) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerEvents_JoinResponse)(nil),
		(*ServerEvents_MessageResponse)(nil),
		(*ServerEvents_Users)(nil),
		(*ServerEvents_UserEvents)(nil),
		(*ServerEvents_ChatMessage)(nil),
		(*ServerEvents_TypingState)(nil),
		(*ServerEvents_MessageUpdate)(nil),
	}
}

func init() {
	proto.RegisterEnum("chaty.UserEvents_Events", UserEvents_Events_name, UserEvents_Events_value)
	proto.RegisterType((*JoinRequest)(nil), "chaty.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "chaty.JoinResponse")
	proto.RegisterType((*ChatMessage)(nil), "chaty.ChatMessage")
	proto.RegisterType((*MessageUpdate)(nil), "chaty.MessageUpdate")
	proto.RegisterType((*ReadMessage)(nil), "chaty.ReadMessage")
	proto.RegisterType((*MessageResponse)(nil), "chaty.MessageResponse")
	proto.RegisterType((*User)(nil), "chaty.User")
	proto.RegisterType((*Users)(nil), "chaty.Users")
	proto.RegisterType((*UserEvents)(nil), "chaty.UserEvents")
	proto.RegisterType((*TypingState)(nil), "chaty.TypingState")
	proto.RegisterType((*ListUsers)(nil), "chaty.ListUsers")
	proto.RegisterType((*ClientEvents)(nil), "chaty.ClientEvents")
	proto.RegisterType((*ServerEvents)(nil), "chaty.ServerEvents")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0x4e, 0xda, 0x26, 0x6d, 0x4e, 0xba, 0xad, 0xaf, 0x5f, 0x34, 0x45, 0x13, 0x42, 0xc3, 0x20,
	0x51, 0xb8, 0x28, 0x55, 0x27, 0x81, 0xf8, 0xb8, 0xa1, 0x15, 0x28, 0x20, 0x3e, 0x24, 0x8f, 0xdd,
	0x70, 0x17, 0x5a, 0xb3, 0xb9, 0xb4, 0x49, 0x89, 0xdd, 0x89, 0xfd, 0x0d, 0xfe, 0x00, 0xd7, 0xfc,
	0x4b, 0xe4, 0x8f, 0x24, 0x4e, 0x50, 0x11, 0xda, 0x55, 0x6c, 0x9f, 0xe7, 0x39, 0xc7, 0xe7, 0x39,
	0x8f, 0x5b, 0x08, 0x92, 0x0d, 0x1b, 0x6d, 0xf2, 0x4c, 0x64, 0xc8, 0x9b, 0x5f, 0x24, 0xe2, 0x0a,
	0xdf, 0x87, 0xf0, 0x4d, 0xc6, 0x52, 0x42, 0xbf, 0x6d, 0x29, 0x17, 0xe8, 0x08, 0x7a, 0x5b, 0x4e,
	0xf3, 0xf7, 0xc9, 0x9a, 0x46, 0xee, 0xb1, 0x3b, 0x0c, 0x48, 0xb9, 0xc7, 0x53, 0xe8, 0x6b, 0x28,
	0xdf, 0x64, 0x29, 0xa7, 0x7f, 0xc3, 0xa2, 0x43, 0xf0, 0xe5, 0xfa, 0xf5, 0x22, 0x6a, 0xa9, 0x88,
	0xd9, 0x61, 0x0a, 0xe1, 0xec, 0x22, 0x11, 0xef, 0x28, 0xe7, 0xc9, 0xb9, 0x0d, 0x73, 0x6d, 0x58,
	0x2d, 0x75, 0xab, 0x91, 0x1a, 0x41, 0x47, 0xd0, 0xef, 0x22, 0x6a, 0xab, 0x73, 0xb5, 0x46, 0xfb,
	0xd0, 0x62, 0x8b, 0xa8, 0xa3, 0x4e, 0x5a, 0x6c, 0x81, 0xef, 0xc1, 0x9e, 0x29, 0x71, 0xb6, 0x59,
	0x24, 0x42, 0x15, 0x62, 0x9c, 0xd0, 0x44, 0x17, 0xea, 0x11, 0xb3, 0xc3, 0xcf, 0x20, 0x94, 0xdf,
	0xe2, 0x3e, 0x3a, 0x8f, 0x5b, 0xe4, 0x41, 0x37, 0x21, 0x58, 0xeb, 0x50, 0xd9, 0x49, 0x75, 0x80,
	0x67, 0x70, 0x60, 0x88, 0xa5, 0x26, 0x08, 0x3a, 0x8c, 0x7f, 0xf8, 0x6a, 0xaa, 0xa8, 0xb5, 0x4c,
	0x92, 0x6b, 0x79, 0xab, 0x24, 0xe5, 0x01, 0x7e, 0x0a, 0x9d, 0x33, 0x4e, 0xf3, 0xeb, 0x48, 0x81,
	0x1f, 0x80, 0x27, 0xb9, 0x1c, 0xdd, 0x06, 0x4f, 0x1e, 0xf2, 0xc8, 0x3d, 0x6e, 0x0f, 0xc3, 0x49,
	0x38, 0x52, 0xc3, 0x1d, 0xc9, 0x20, 0xd1, 0x11, 0xfc, 0xc3, 0x05, 0x90, 0xfb, 0x97, 0x97, 0x34,
	0x15, 0x7c, 0x67, 0xb9, 0x31, 0xf8, 0x54, 0x21, 0x54, 0xb1, 0xfd, 0x49, 0x64, 0xa5, 0xd2, 0xd4,
	0x91, 0xfe, 0x10, 0x83, 0xab, 0x5d, 0xb0, 0xdd, 0xb8, 0xe0, 0x2d, 0xf0, 0x4d, 0x3d, 0x00, 0x7f,
	0x99, 0xb1, 0x94, 0x2e, 0x06, 0x0e, 0xea, 0x41, 0x67, 0x45, 0xbf, 0x88, 0x81, 0x8b, 0x5f, 0x40,
	0xf8, 0xf1, 0x6a, 0xc3, 0xd2, 0xf3, 0x53, 0x61, 0xa6, 0xb4, 0x4b, 0x03, 0xc6, 0x35, 0x50, 0x5d,
	0xab, 0x47, 0xca, 0x3d, 0xbe, 0x03, 0xc1, 0x5b, 0xc6, 0x85, 0xd6, 0x61, 0x47, 0x02, 0xfc, 0xab,
	0x05, 0xfd, 0xd9, 0x8a, 0xd1, 0x54, 0x98, 0xeb, 0x3c, 0x82, 0x70, 0x59, 0xd9, 0x5e, 0xa1, 0xc3,
	0x09, 0x32, 0xbd, 0x5a, 0x0f, 0x22, 0x76, 0x88, 0x0d, 0x94, 0xbc, 0x79, 0xe5, 0x5f, 0x75, 0x99,
	0x8a, 0x67, 0x39, 0x5b, 0xf2, 0x2c, 0xa0, 0xe4, 0x89, 0xaa, 0x51, 0xa5, 0x53, 0xc5, 0xb3, 0x24,
	0x90, 0x3c, 0x0b, 0x88, 0xc6, 0x10, 0xac, 0x8a, 0xee, 0x94, 0xbf, 0xc3, 0xc9, 0xc0, 0xb0, 0xca,
	0xae, 0x63, 0x87, 0x54, 0x20, 0x59, 0x29, 0xaf, 0x1c, 0x1d, 0x79, 0xb5, 0x4a, 0x96, 0xd7, 0x65,
	0x25, 0x0b, 0x38, 0xed, 0x82, 0xa7, 0x06, 0x8a, 0x7f, 0xb6, 0xa1, 0x7f, 0x4a, 0xf3, 0xcb, 0xd2,
	0x2a, 0x4f, 0xa0, 0xbf, 0xb4, 0xde, 0xbd, 0x11, 0xeb, 0xff, 0x9a, 0x58, 0x3a, 0x14, 0x3b, 0xa4,
	0x06, 0x45, 0x53, 0x38, 0x58, 0xd7, 0x5f, 0x88, 0x91, 0xec, 0xd0, 0xb0, 0x1b, 0xef, 0x27, 0x76,
	0x48, 0x93, 0x80, 0xee, 0x16, 0xde, 0xd6, 0xa2, 0xf5, 0x2d, 0x43, 0xca, 0xd6, 0x75, 0x10, 0x9d,
	0x00, 0x6c, 0x4b, 0x8b, 0x1a, 0xa5, 0xfe, 0xfb, 0xc3, 0xbb, 0xb1, 0x43, 0x2c, 0x58, 0x73, 0x9a,
	0xde, 0x35, 0xa7, 0xe9, 0xff, 0xeb, 0x34, 0x9f, 0xc3, 0xde, 0xda, 0xfe, 0x59, 0x8a, 0xba, 0x8a,
	0x79, 0xa3, 0x2e, 0x86, 0x8e, 0xc5, 0x0e, 0xa9, 0x83, 0xcb, 0x09, 0x4d, 0x5e, 0xe9, 0x1f, 0x51,
	0x39, 0x24, 0x36, 0xa7, 0xe8, 0x31, 0x74, 0x67, 0x59, 0x9a, 0xd2, 0xb9, 0x40, 0xc5, 0x50, 0x6c,
	0xaf, 0x1f, 0x15, 0x87, 0xf6, 0x50, 0x87, 0xee, 0xd8, 0x9d, 0x06, 0x9f, 0xba, 0xa3, 0x87, 0xea,
	0xdf, 0xe0, 0xb3, 0xaf, 0x3e, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x95, 0xd1, 0xb0,
	0x21, 0x06, 0x00, 0x00,
}
