// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserEvents_Events int32

const (
	UserEvents_joined UserEvents_Events = 0
	UserEvents_left   UserEvents_Events = 1
)

var UserEvents_Events_name = map[int32]string{
	0: "joined",
	1: "left",
}

var UserEvents_Events_value = map[string]int32{
	"joined": 0,
	"left":   1,
}

func (x UserEvents_Events) String() string {
	return proto.EnumName(UserEvents_Events_name, int32(x))
}

func (UserEvents_Events) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8, 0}
}

type JoinRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type JoinResponse struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *JoinResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ChatMessage struct {
	SenderName           string   `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *ChatMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MessageRequest struct {
	UserId               string       `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message              *ChatMessage `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string       `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MessageRequest) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MessageRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type MessageStatus struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageStatus) Reset()         { *m = MessageStatus{} }
func (m *MessageStatus) String() string { return proto.CompactTextString(m) }
func (*MessageStatus) ProtoMessage()    {}
func (*MessageStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *MessageStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageStatus.Unmarshal(m, b)
}
func (m *MessageStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageStatus.Marshal(b, m, deterministic)
}
func (m *MessageStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageStatus.Merge(m, src)
}
func (m *MessageStatus) XXX_Size() int {
	return xxx_messageInfo_MessageStatus.Size(m)
}
func (m *MessageStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MessageStatus proto.InternalMessageInfo

func (m *MessageStatus) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type MessageResponse struct {
	MessageStatus        *MessageStatus `protobuf:"bytes,1,opt,name=message_status,json=messageStatus,proto3" json:"message_status,omitempty"`
	RequestId            string         `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetMessageStatus() *MessageStatus {
	if m != nil {
		return m.MessageStatus
	}
	return nil
}

func (m *MessageResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserEvents struct {
	User                 *User             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Events               UserEvents_Events `protobuf:"varint,2,opt,name=events,proto3,enum=chaty.UserEvents_Events" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserEvents) Reset()         { *m = UserEvents{} }
func (m *UserEvents) String() string { return proto.CompactTextString(m) }
func (*UserEvents) ProtoMessage()    {}
func (*UserEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *UserEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvents.Unmarshal(m, b)
}
func (m *UserEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvents.Marshal(b, m, deterministic)
}
func (m *UserEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvents.Merge(m, src)
}
func (m *UserEvents) XXX_Size() int {
	return xxx_messageInfo_UserEvents.Size(m)
}
func (m *UserEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvents.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvents proto.InternalMessageInfo

func (m *UserEvents) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserEvents) GetEvents() UserEvents_Events {
	if m != nil {
		return m.Events
	}
	return UserEvents_joined
}

type TypingState struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsTyping             bool     `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypingState) Reset()         { *m = TypingState{} }
func (m *TypingState) String() string { return proto.CompactTextString(m) }
func (*TypingState) ProtoMessage()    {}
func (*TypingState) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *TypingState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypingState.Unmarshal(m, b)
}
func (m *TypingState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypingState.Marshal(b, m, deterministic)
}
func (m *TypingState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypingState.Merge(m, src)
}
func (m *TypingState) XXX_Size() int {
	return xxx_messageInfo_TypingState.Size(m)
}
func (m *TypingState) XXX_DiscardUnknown() {
	xxx_messageInfo_TypingState.DiscardUnknown(m)
}

var xxx_messageInfo_TypingState proto.InternalMessageInfo

func (m *TypingState) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TypingState) GetIsTyping() bool {
	if m != nil {
		return m.IsTyping
	}
	return false
}

type ListUsers struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsers) Reset()         { *m = ListUsers{} }
func (m *ListUsers) String() string { return proto.CompactTextString(m) }
func (*ListUsers) ProtoMessage()    {}
func (*ListUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ListUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsers.Unmarshal(m, b)
}
func (m *ListUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsers.Marshal(b, m, deterministic)
}
func (m *ListUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsers.Merge(m, src)
}
func (m *ListUsers) XXX_Size() int {
	return xxx_messageInfo_ListUsers.Size(m)
}
func (m *ListUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsers.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsers proto.InternalMessageInfo

func (m *ListUsers) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ClientEvents struct {
	// Types that are valid to be assigned to Event:
	//	*ClientEvents_JoinRequest
	//	*ClientEvents_MessageRequest
	//	*ClientEvents_Typing_State
	//	*ClientEvents_ListUsers
	Event                isClientEvents_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClientEvents) Reset()         { *m = ClientEvents{} }
func (m *ClientEvents) String() string { return proto.CompactTextString(m) }
func (*ClientEvents) ProtoMessage()    {}
func (*ClientEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ClientEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientEvents.Unmarshal(m, b)
}
func (m *ClientEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientEvents.Marshal(b, m, deterministic)
}
func (m *ClientEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientEvents.Merge(m, src)
}
func (m *ClientEvents) XXX_Size() int {
	return xxx_messageInfo_ClientEvents.Size(m)
}
func (m *ClientEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ClientEvents proto.InternalMessageInfo

type isClientEvents_Event interface {
	isClientEvents_Event()
}

type ClientEvents_JoinRequest struct {
	JoinRequest *JoinRequest `protobuf:"bytes,1,opt,name=joinRequest,proto3,oneof"`
}

type ClientEvents_MessageRequest struct {
	MessageRequest *MessageRequest `protobuf:"bytes,2,opt,name=messageRequest,proto3,oneof"`
}

type ClientEvents_Typing_State struct {
	Typing_State *TypingState `protobuf:"bytes,3,opt,name=typing_State,json=typingState,proto3,oneof"`
}

type ClientEvents_ListUsers struct {
	ListUsers *ListUsers `protobuf:"bytes,4,opt,name=list_users,json=listUsers,proto3,oneof"`
}

func (*ClientEvents_JoinRequest) isClientEvents_Event() {}

func (*ClientEvents_MessageRequest) isClientEvents_Event() {}

func (*ClientEvents_Typing_State) isClientEvents_Event() {}

func (*ClientEvents_ListUsers) isClientEvents_Event() {}

func (m *ClientEvents) GetEvent() isClientEvents_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ClientEvents) GetJoinRequest() *JoinRequest {
	if x, ok := m.GetEvent().(*ClientEvents_JoinRequest); ok {
		return x.JoinRequest
	}
	return nil
}

func (m *ClientEvents) GetMessageRequest() *MessageRequest {
	if x, ok := m.GetEvent().(*ClientEvents_MessageRequest); ok {
		return x.MessageRequest
	}
	return nil
}

func (m *ClientEvents) GetTyping_State() *TypingState {
	if x, ok := m.GetEvent().(*ClientEvents_Typing_State); ok {
		return x.Typing_State
	}
	return nil
}

func (m *ClientEvents) GetListUsers() *ListUsers {
	if x, ok := m.GetEvent().(*ClientEvents_ListUsers); ok {
		return x.ListUsers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientEvents) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientEvents_JoinRequest)(nil),
		(*ClientEvents_MessageRequest)(nil),
		(*ClientEvents_Typing_State)(nil),
		(*ClientEvents_ListUsers)(nil),
	}
}

type ServerEvents struct {
	// Types that are valid to be assigned to Event:
	//	*ServerEvents_JoinResponse
	//	*ServerEvents_MessageResponse
	//	*ServerEvents_Users
	//	*ServerEvents_UserEvents
	//	*ServerEvents_ChatMessage
	//	*ServerEvents_TypingState
	Event                isServerEvents_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ServerEvents) Reset()         { *m = ServerEvents{} }
func (m *ServerEvents) String() string { return proto.CompactTextString(m) }
func (*ServerEvents) ProtoMessage()    {}
func (*ServerEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ServerEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerEvents.Unmarshal(m, b)
}
func (m *ServerEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerEvents.Marshal(b, m, deterministic)
}
func (m *ServerEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerEvents.Merge(m, src)
}
func (m *ServerEvents) XXX_Size() int {
	return xxx_messageInfo_ServerEvents.Size(m)
}
func (m *ServerEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ServerEvents proto.InternalMessageInfo

type isServerEvents_Event interface {
	isServerEvents_Event()
}

type ServerEvents_JoinResponse struct {
	JoinResponse *JoinResponse `protobuf:"bytes,1,opt,name=joinResponse,proto3,oneof"`
}

type ServerEvents_MessageResponse struct {
	MessageResponse *MessageResponse `protobuf:"bytes,2,opt,name=messageResponse,proto3,oneof"`
}

type ServerEvents_Users struct {
	Users *Users `protobuf:"bytes,3,opt,name=users,proto3,oneof"`
}

type ServerEvents_UserEvents struct {
	UserEvents *UserEvents `protobuf:"bytes,4,opt,name=user_events,json=userEvents,proto3,oneof"`
}

type ServerEvents_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,5,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type ServerEvents_TypingState struct {
	TypingState *TypingState `protobuf:"bytes,6,opt,name=typing_state,json=typingState,proto3,oneof"`
}

func (*ServerEvents_JoinResponse) isServerEvents_Event() {}

func (*ServerEvents_MessageResponse) isServerEvents_Event() {}

func (*ServerEvents_Users) isServerEvents_Event() {}

func (*ServerEvents_UserEvents) isServerEvents_Event() {}

func (*ServerEvents_ChatMessage) isServerEvents_Event() {}

func (*ServerEvents_TypingState) isServerEvents_Event() {}

func (m *ServerEvents) GetEvent() isServerEvents_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ServerEvents) GetJoinResponse() *JoinResponse {
	if x, ok := m.GetEvent().(*ServerEvents_JoinResponse); ok {
		return x.JoinResponse
	}
	return nil
}

func (m *ServerEvents) GetMessageResponse() *MessageResponse {
	if x, ok := m.GetEvent().(*ServerEvents_MessageResponse); ok {
		return x.MessageResponse
	}
	return nil
}

func (m *ServerEvents) GetUsers() *Users {
	if x, ok := m.GetEvent().(*ServerEvents_Users); ok {
		return x.Users
	}
	return nil
}

func (m *ServerEvents) GetUserEvents() *UserEvents {
	if x, ok := m.GetEvent().(*ServerEvents_UserEvents); ok {
		return x.UserEvents
	}
	return nil
}

func (m *ServerEvents) GetChatMessage() *ChatMessage {
	if x, ok := m.GetEvent().(*ServerEvents_ChatMessage); ok {
		return x.ChatMessage
	}
	return nil
}

func (m *ServerEvents) GetTypingState() *TypingState {
	if x, ok := m.GetEvent().(*ServerEvents_TypingState); ok {
		return x.TypingState
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerEvents) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerEvents_JoinResponse)(nil),
		(*ServerEvents_MessageResponse)(nil),
		(*ServerEvents_Users)(nil),
		(*ServerEvents_UserEvents)(nil),
		(*ServerEvents_ChatMessage)(nil),
		(*ServerEvents_TypingState)(nil),
	}
}

func init() {
	proto.RegisterEnum("chaty.UserEvents_Events", UserEvents_Events_name, UserEvents_Events_value)
	proto.RegisterType((*JoinRequest)(nil), "chaty.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "chaty.JoinResponse")
	proto.RegisterType((*ChatMessage)(nil), "chaty.ChatMessage")
	proto.RegisterType((*MessageRequest)(nil), "chaty.MessageRequest")
	proto.RegisterType((*MessageStatus)(nil), "chaty.MessageStatus")
	proto.RegisterType((*MessageResponse)(nil), "chaty.MessageResponse")
	proto.RegisterType((*User)(nil), "chaty.User")
	proto.RegisterType((*Users)(nil), "chaty.Users")
	proto.RegisterType((*UserEvents)(nil), "chaty.UserEvents")
	proto.RegisterType((*TypingState)(nil), "chaty.TypingState")
	proto.RegisterType((*ListUsers)(nil), "chaty.ListUsers")
	proto.RegisterType((*ClientEvents)(nil), "chaty.ClientEvents")
	proto.RegisterType((*ServerEvents)(nil), "chaty.ServerEvents")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5b, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xba, 0x24, 0x6d, 0x4e, 0xb2, 0x0b, 0x1e, 0x97, 0x0a, 0x04, 0x1b, 0xd6, 0x1e, 0xaa,
	0x09, 0x95, 0x51, 0x10, 0x13, 0x62, 0x12, 0x52, 0x07, 0x52, 0xc7, 0x55, 0xf2, 0xe0, 0x85, 0x97,
	0x28, 0xac, 0x66, 0xf3, 0xd6, 0x24, 0xa5, 0x76, 0x2b, 0xfa, 0xc4, 0x9f, 0xe5, 0x67, 0xf0, 0x80,
	0x7c, 0x49, 0xea, 0x04, 0x75, 0xe2, 0x29, 0xb1, 0xcf, 0x77, 0x8e, 0xcf, 0xf7, 0x7d, 0xc7, 0x86,
	0x20, 0x99, 0xb0, 0xde, 0x64, 0x9a, 0x8b, 0x1c, 0x79, 0x67, 0x17, 0x89, 0x58, 0xe0, 0x7d, 0x08,
	0xdf, 0xe6, 0x2c, 0x23, 0xf4, 0xc7, 0x8c, 0x72, 0x81, 0xee, 0x41, 0x30, 0xe3, 0x74, 0x1a, 0x67,
	0x49, 0x4a, 0x3b, 0xce, 0xae, 0xd3, 0x0d, 0x48, 0x5b, 0x6e, 0x7c, 0x4c, 0x52, 0x8a, 0x5f, 0x43,
	0xa4, 0xb1, 0x7c, 0x92, 0x67, 0x9c, 0x5e, 0x0b, 0x46, 0x77, 0xa0, 0xa5, 0x82, 0x6c, 0xd4, 0x69,
	0xaa, 0x90, 0x2f, 0x97, 0x27, 0x23, 0x3c, 0x80, 0xf0, 0xf8, 0x22, 0x11, 0x1f, 0x28, 0xe7, 0xc9,
	0x39, 0x45, 0x3b, 0x10, 0x72, 0x9a, 0x8d, 0xaa, 0x65, 0x40, 0x6f, 0xa9, 0x42, 0x08, 0x5c, 0x41,
	0x7f, 0x0a, 0x53, 0x45, 0xfd, 0xe3, 0x39, 0x6c, 0x98, 0xfc, 0xa2, 0xf1, 0x55, 0xc7, 0xa1, 0x47,
	0xd0, 0x4a, 0x35, 0xb4, 0xb3, 0xb6, 0xeb, 0x74, 0xc3, 0x3e, 0xea, 0x29, 0xe6, 0x3d, 0xab, 0x09,
	0x52, 0x40, 0xd0, 0x7d, 0x80, 0xa9, 0xae, 0x28, 0x2b, 0xb9, 0xaa, 0x52, 0x60, 0x76, 0x4e, 0x46,
	0x78, 0x0f, 0xd6, 0x4d, 0xca, 0xa9, 0x48, 0xc4, 0x8c, 0xa3, 0x6d, 0xf0, 0x18, 0x8f, 0xf3, 0x2b,
	0xd5, 0x77, 0x9b, 0xb8, 0x8c, 0x7f, 0xba, 0xc2, 0x29, 0x6c, 0x96, 0xdd, 0x19, 0xa9, 0x5e, 0xc2,
	0x86, 0x39, 0x22, 0xe6, 0x2a, 0x53, 0x25, 0x84, 0xfd, 0x9b, 0xa6, 0x99, 0x4a, 0x55, 0xb2, 0x9e,
	0x56, 0x0e, 0xa9, 0x36, 0xd5, 0xac, 0x37, 0x75, 0x04, 0xee, 0x17, 0x4e, 0xa7, 0xb6, 0x04, 0x4e,
	0x45, 0x82, 0x8a, 0x4f, 0xcd, 0x9a, 0xa9, 0xfb, 0xe0, 0xc9, 0x6c, 0x8e, 0x1e, 0x82, 0x27, 0x37,
	0x65, 0x67, 0x6b, 0xdd, 0xb0, 0x1f, 0x9a, 0xce, 0x64, 0x90, 0xe8, 0x08, 0xfe, 0x05, 0x20, 0x97,
	0x6f, 0xe6, 0x34, 0x13, 0x1c, 0xed, 0x80, 0x2b, 0xb7, 0x0d, 0x93, 0x0a, 0x5e, 0x05, 0xd0, 0x01,
	0xf8, 0x54, 0x41, 0xd5, 0xa1, 0x1b, 0xfd, 0x8e, 0x05, 0xd1, 0x35, 0x7a, 0xfa, 0x43, 0x0c, 0x0e,
	0x3f, 0x00, 0xdf, 0x14, 0x07, 0xf0, 0x2f, 0x73, 0x96, 0xd1, 0xd1, 0x56, 0x03, 0xb5, 0xc1, 0x1d,
	0xd3, 0xef, 0x62, 0xcb, 0xc1, 0xc7, 0x10, 0x7e, 0x5e, 0x4c, 0x58, 0x76, 0x2e, 0x95, 0xa1, 0xd7,
	0x32, 0x66, 0x3c, 0x16, 0x0a, 0xaa, 0x0e, 0x6f, 0x93, 0x36, 0xe3, 0x3a, 0x15, 0xef, 0x41, 0xf0,
	0x9e, 0x71, 0xa1, 0x59, 0xaf, 0x2a, 0x81, 0xff, 0x38, 0x10, 0x1d, 0x8f, 0x19, 0xcd, 0x84, 0xe9,
	0xe8, 0x39, 0x84, 0x97, 0xcb, 0x9b, 0x62, 0x58, 0x17, 0xc3, 0x64, 0xdd, 0xa1, 0x61, 0x83, 0xd8,
	0x40, 0xf4, 0xaa, 0xb4, 0xbe, 0x48, 0x6d, 0xaa, 0xd4, 0x5b, 0x55, 0xeb, 0x97, 0xd9, 0x35, 0x38,
	0x3a, 0x84, 0x48, 0x33, 0x89, 0x15, 0xeb, 0xda, 0x18, 0x5b, 0x7a, 0xc8, 0x93, 0x85, 0x25, 0xcf,
	0x13, 0x80, 0x31, 0xe3, 0x22, 0xd6, 0xb6, 0xba, 0x2a, 0x6d, 0xcb, 0xa4, 0x95, 0x0a, 0x0c, 0x1b,
	0x24, 0x18, 0x17, 0x8b, 0x41, 0x0b, 0x3c, 0x65, 0x05, 0xfe, 0xdd, 0x84, 0xe8, 0x94, 0x4e, 0xe7,
	0xa5, 0xdb, 0x2f, 0x20, 0xba, 0xb4, 0x2e, 0xbf, 0xe1, 0xbf, 0x5d, 0xe1, 0xaf, 0x43, 0xc3, 0x06,
	0xa9, 0x40, 0xd1, 0x00, 0x36, 0xd3, 0xea, 0x7d, 0x30, 0x12, 0xdc, 0xae, 0x4b, 0x50, 0x16, 0xa8,
	0x27, 0xa0, 0xbd, 0x62, 0x3a, 0x35, 0xfb, 0xc8, 0x1a, 0x25, 0x49, 0x41, 0x07, 0xd1, 0x33, 0x08,
	0x95, 0x9b, 0x66, 0xec, 0x34, 0xe5, 0x1b, 0xff, 0x8c, 0xdd, 0xb0, 0x41, 0x60, 0xb6, 0x1c, 0xe4,
	0x43, 0x88, 0x24, 0x22, 0x2e, 0xde, 0x09, 0x6f, 0xd5, 0x3b, 0x21, 0x05, 0x3e, 0xb3, 0xde, 0xae,
	0xa5, 0x33, 0x5c, 0x39, 0xe3, 0xff, 0xa7, 0x33, 0xa5, 0xcc, 0xfd, 0x77, 0xfa, 0x31, 0x94, 0x4a,
	0xb3, 0x33, 0x8a, 0x8e, 0x20, 0x92, 0xcb, 0x45, 0xb1, 0x2e, 0xe4, 0xb5, 0x07, 0xf1, 0x6e, 0xb1,
	0x69, 0xdb, 0xd3, 0x75, 0x0e, 0x9c, 0x41, 0xf0, 0xb5, 0xd5, 0x7b, 0xac, 0x5e, 0xf7, 0x6f, 0xbe,
	0xfa, 0x3c, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x80, 0xe8, 0x8f, 0x9f, 0xf1, 0x05, 0x00, 0x00,
}
